security:
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        Yoda\UserBundle\Entity\User: bcrypt

    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_EVENT_CREATE, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        our_database_users:
#            entity: { class: UserBundle:User, property: username }
            # more flexible: username or email : UserProvider
            entity: { class: UserBundle:User }

    # path: url or route_name
    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login_form
            logout:
                path:   logout
                target: event
            anonymous: ~
            switch_user: ~
            remember_me:
                key: "Order 1138"
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
    # to controller - secruity.context
#        - { path: ^/new, roles: ROLE_USER }
#        - { path: ^/create, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # to enable forced login user
#        - { path: ^/, roles: ROLE_USER }
